### PR TITLE
Sundhar dev

### PR DESCRIPTION
**Pull request by sundharm**
[AB#111](https://dev.azure.com/Tringo/cabcbfb6-3a22-44cf-ac98-b3810925a870/_workitems/edit/111)
Removed date picker and unknown dates panel. Added month selector. Please check if I have removed everything properly. Let me know if anything has to be changed.

### CODE REVIEW

**Review by s3419069 — APPROVED** [review]

**Comment by rmit-s3668804-Dzmitry-Kakaruk** [comment]
I think the card should deactivate itself on exit (see comments on the card in VS

**Comment by sundharm** [comment]
The selector deactivates on exit and colors are now same as the other components

**Comment by rmit-s3668804-Dzmitry-Kakaruk** [comment]
@sundharm  Yeah, you changed the look but you broke the data contract, now no price markers are coming back from API

**Comment by sundharm** [comment]
I think it needs duration as well to display the markers, no?

**Pull request merged**
