### PR TITLE
price marker display update

### PR DESCRIPTION
**Pull request by SimonChow9527**
[AB#130](https://dev.azure.com/Tringo/cabcbfb6-3a22-44cf-ac98-b3810925a870/_workitems/edit/130)

### CODE REVIEW

**Comment by rmit-s3668804-Dzmitry-Kakaruk** [comment]
that's a miss 
image


look how at Webjet they play with font sizes etc. 
image

**Review by rmit-s3668804-Dzmitry-Kakaruk — APPROVED** [review]
could look better, make from all lowercase, not bold and smaller font size,
also replace + with * and make it superscript

**Comment by SimonChow9527** [comment]
marker
now it looks like this

**Comment by s3419069** [comment]
looks odd. Why does it higher than price and sticks to left side..
Should it be * instead of +?
(sorry, didn't meant to close) however, it's not yet ready to be merged anyway

**Comment by SimonChow9527** [comment]
marker2
marker2
now like this

**Comment by rmit-s3668804-Dzmitry-Kakaruk** [comment]
Align to the left edge

**Comment by SimonChow9527** [comment]
marker3
now this

**Pull request merged**
